/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

/**
 *
 * @author Usuario
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jButtonMinimizar = new javax.swing.JButton();
        jButtonSalirMenu = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonAgregar3 = new javax.swing.JButton();
        jButtonAgregar4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBorder(null);
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 30, 30));

        jButtonMinimizar.setBorder(null);
        jButtonMinimizar.setBorderPainted(false);
        jButtonMinimizar.setContentAreaFilled(false);
        jButtonMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 30, -1));

        jButtonSalirMenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSalirMenu.setForeground(new java.awt.Color(255, 0, 51));
        jButtonSalirMenu.setText("Salir");
        jButtonSalirMenu.setContentAreaFilled(false);
        jButtonSalirMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        jButtonAgregar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(255, 0, 0));
        jButtonAgregar.setText("Buscar Comprobante\n");
        jButtonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAgregar.setIconTextGap(-3);
        jButtonAgregar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButtonAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 250, 60));

        jButtonAgregar3.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgregar3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAgregar3.setForeground(new java.awt.Color(255, 0, 0));
        jButtonAgregar3.setText("Lista de Clientes");
        jButtonAgregar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAgregar3.setIconTextGap(-3);
        jButtonAgregar3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButtonAgregar3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 250, 60));

        jButtonAgregar4.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgregar4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAgregar4.setForeground(new java.awt.Color(255, 0, 0));
        jButtonAgregar4.setText("Agregar cliente/comercio ");
        jButtonAgregar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregar4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAgregar4.setIconTextGap(-3);
        jButtonAgregar4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButtonAgregar4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAgregar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 250, 60));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMinimizarActionPerformed

    private void jButtonAgregar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar4ActionPerformed
        // TODO add your handling code here:
        AgregarClienteComercio ventanaClienteComercio = new AgregarClienteComercio();
        ventanaClienteComercio.setVisible(true);
    }//GEN-LAST:event_jButtonAgregar4ActionPerformed

    private void jButtonSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirMenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirMenuActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar3ActionPerformed
        // TODO add your handling code here:
        VerListaDeClientes ventanaListaDeClientes = new VerListaDeClientes();
        ventanaListaDeClientes.setVisible(true);
    }//GEN-LAST:event_jButtonAgregar3ActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        BuscarPorNumeroDeComprobante ventanaBusqueda = new BuscarPorNumeroDeComprobante();
        ventanaBusqueda.setVisible(true);
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAgregar3;
    private javax.swing.JButton jButtonAgregar4;
    private javax.swing.JButton jButtonMinimizar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSalirMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
